### ISSUE TITLE
Can you release builtinvotes.ext.2.l4d2.dll for windows please?

### ISSUE THREAD

**Issue by fbef0102** [A1mDev/builtinvotes#2]
I don't know how to compile .dll,
if you can release windows version too, I will appreciate.

Edit: I need it because I use the lastest [readyup.sp](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/readyup.sp) from sirplease

**Comment by A1mDev** [comment]
What is your version of sourcemod?

**Comment by A1mDev** [comment]
@fbef0102, What is your version of sourcemod?

**Comment by fbef0102** [comment]
sm1.10 - stable build 6502
meta1.11 - stable build 1144

**Comment by A1mDev** [comment]
Added windows version - https://github.com/A1mDev/builtinvotes/releases/tag/0.6.4. If you have problems, please contact.
